services:
  nuxt3-tailwindcss:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app/
      - node_modules:/home/node/app/node_modules/
volumes:
  node_modules: {}